services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tagit
      MONGO_INITDB_ROOT_PASSWORD: tagit_password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: